USE [master]
GO

/****** Object:  Database [destinstionDW]    Script Date: 1/28/2024 1:58:02 PM ******/
CREATE DATABASE [destinstionDW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'destinstionDW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\destinstionDW.mdf' , SIZE = 335872KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'destinstionDW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\destinstionDW_log.ldf' , SIZE = 401408KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [destinstionDW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [destinstionDW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [destinstionDW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [destinstionDW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [destinstionDW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [destinstionDW] SET ARITHABORT OFF 
GO

ALTER DATABASE [destinstionDW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [destinstionDW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [destinstionDW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [destinstionDW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [destinstionDW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [destinstionDW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [destinstionDW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [destinstionDW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [destinstionDW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [destinstionDW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [destinstionDW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [destinstionDW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [destinstionDW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [destinstionDW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [destinstionDW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [destinstionDW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [destinstionDW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [destinstionDW] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [destinstionDW] SET  MULTI_USER 
GO

ALTER DATABASE [destinstionDW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [destinstionDW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [destinstionDW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [destinstionDW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [destinstionDW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [destinstionDW] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [destinstionDW] SET QUERY_STORE = ON
GO

ALTER DATABASE [destinstionDW] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [destinstionDW] SET  READ_WRITE 
GO

